# https://stylelint.io

plugins:
  - stylelint-scss
  - stylelint-a11y

syntax:
  - scss

extends:
  # standard > recommended
  - stylelint-config-standard
  # Order by properties
  - stylelint-config-recess-order

rules:
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
  no-empty-source: null
  selector-class-pattern: "^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"
  no-invalid-position-at-import-rule: null
