language: node_js

stages:
  - lint
  - compile

node_js:
  - "12"

cache: npm

jobs:
  include:
    # ESLint
    - stage: "lint"
      name: "ESLint"
      install:
        - |
          npm install eslint \
          eslint-plugin-vue \
          @nekohack/eslint-config \
          typescript \
          @typescript-eslint/parser \
          @typescript-eslint/typescript-estree
      script:
        - npm run lint
    # Build Compile
    - stage: "compile"
      name: "Build Compile"
      before_install:
        - if [[ $TRAVIS_NODE_VERSION == 8 ]]; then npm i -g npm@latest; fi
      install:
        - rm -rf node_modules && npm install
      script:
        - npm run build
