version: '3'
services:
  webneko_blog_front:
    container_name: webneko_blog_front
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/src:cached
      # exclude volumes
      - /node_modules
    tty: true
    stdin_open: true
    env_file: ./.env
    environment:
      # enabled HMR
      - CHOKIDAR_USEPOLLING=true
