export const CATEGORIES = [
  {id: 1, name: 'Web', backgroundColor: '#0033ff', color: '#fff'},
  {id: 2, name: 'HTML5', backgroundColor: '#0099ff', color: '#000'},
  {id: 3, name: 'CSS', backgroundColor: '#00ff99', color: '#000'},
  {id: 4, name: 'Javascript', backgroundColor: '#ffff00', color: '#000'},
  {id: 5, name: 'EcmaScript', backgroundColor: '#ff9966', color: '#000'},
  {id: 6, name: 'PHP', backgroundColor: '#000099', color: '#fff'},
  {id: 7, name: 'Zendframework', backgroundColor: '#009933', color: '#fff'},
  {id: 8, name: 'Laravel', backgroundColor: '#ff99cc', color: '#000'},
  {id: 9, name: 'Scala', backgroundColor: '#ff0000', color: '#fff'},
  {id: 10, name: 'Playframework', backgroundColor: '#666666', color: '#fff'},
  {id: 11, name: 'Kotlin', backgroundColor: '#ffcc33', color: '#000'},
  {id: 12, name: 'Sparkframework', backgroundColor: '#cccccc', color: '#000'},
  {id: 13, name: 'Heroku', backgroundColor: '#ccffff', color: '#000'},
  {id: 14, name: 'Netlify', backgroundColor: '#99ffcc', color: '#000'},
  {id: 15, name: 'AWS', backgroundColor: '#660000', color: '#fff'},
  {id: 16, name: 'React', backgroundColor: '#3300ff', color: '#fff'},
  {id: 17, name: 'Vue', backgroundColor: '#33ff33', color: '#000'},
  {id: 18, name: 'Objective-c', backgroundColor: '#cc9933', color: '#000'},
  {id: 19, name: 'Swift', backgroundColor: '#ff6633', color: '#fff'},
  {id: 20, name: 'Firebase', backgroundColor: '#ff9900', color: '#fff'},
  {id: 21, name: 'TypeScript', backgroundColor: '#ff33ff', color: '#fff'},
  {id: 22, name: 'Nuxt.js', backgroundColor: '#339933', color: '#fff'},
  {id: 23, name: 'VuePress', backgroundColor: '#33ff99', color: '#000'},
  {id: 24, name: 'Gatsby', backgroundColor: '#990099', color: '#fff'},
  {id: 25, name: 'Angular', backgroundColor: '#ff3333', color: '#fff'},
  {id: 26, name: 'Elixir', backgroundColor: '#660099', color: '#fff'},
  {id: 27, name: 'Java', backgroundColor: '#ff6600', color: '#fff'},
  {id: 28, name: 'Docker', backgroundColor: '#1D2088', color: '#fff'},
  {id: 29, name: 'MySQL', backgroundColor: '#ff9933', color: '#fff'},
  {id: 30, name: 'PostgreSQL', backgroundColor: '#333399', color: '#fff'},
  {id: 31, name: 'Redis', backgroundColor: '#cc0000', color: '#fff'},
  {id: 99, name: 'Others', backgroundColor: '#000000', color: '#fff'}
]

// export default {}
