version: 2.1

jobs:
  transpile:
    docker:
      - image: node:12.4.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        key: projectname-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
        name: System information
        command: |
          echo "Node $(node -v)"
          echo "Yarn v$(yarn --version)"
      - run:
        name: Install dependencies
        command: yarn install
      - run:
        name: Transpile
        command: yarn build

workflows:
  version: 2
  build-transpile:
    jobs:
      - transpile:
        filters:
          branches:
            only:
              - master
              - release
