name: Backup CI

on:
  schedule:
    - cron: '0/5 * * * *'
#  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: _cache_npm_node14
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Export posts
        run: |
          npm install
          npm install contentful-cli -g
          contentful login --management-token $CTF_MANAGEMENT_TOKEN
          contentful space export --space-id $CTF_SPACE_ID --content-file webneko-blog-export.json
        env:
          CI: true
          CTF_SPACE_ID: ${{ secrets.CTF_SPACE_ID }}
          CTF_MANAGEMENT_TOKEN: ${{ secrets.CTF_MANAGEMENT_TOKEN }}

      - name: Convert markdown
        run: |
          npm run backup
        env:
          CI: true

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git add .
            git commit -m "Add changes" -a
            git push origin HEAD:${GITHUB_REF};
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
