name: Lighthouse CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Lighthouse CLI Run
        run: |
          npm install && npm install -g @lhci/cli@0.4.x
          npm run build
          lhci autorun
        env:
          CI: true
